# Generated by Django 6.1.1 on 2026-09-14 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_name', models.CharField(default='My Profile', max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(default='Software Developer', max_length=150)),
                ('skills', models.TextField(default='Python, Django, REST APIs, JavaScript, HTML/CSS, SQL, Git')),
                ('experience_years', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('grad_year', models.CharField(blank=True, max_length=10)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('about_me', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/')),
                ('gmail_enc', models.TextField(blank=True)),
                ('app_password_enc', models.TextField(blank=True)),
                ('gemini_key_enc', models.TextField(blank=True)),
                ('gmail_configured', models.BooleanField(default=False)),
                ('gemini_configured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=200)),
                ('theme_used', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=300)),
                ('opening_para', models.TextField(blank=True)),
                ('ai_used', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='failed', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='mailer.profile')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='mailer.profile')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('profile', 'email')},
            },
        ),
    ]
