# Generated by Django 4.2.13 on 2026-09-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience_years',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
