# Generated by Django 4.2.13 on 2026-09-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_emaillog_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lifetime_emails_sent',
            field=models.IntegerField(default=0),
        ),
    ]
