# Generated by Django 4.2.13 on 2026-09-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_profile_lifetime_emails_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lifetime_emails_sent',
        ),
        migrations.AddField(
            model_name='profile',
            name='default_tone',
            field=models.CharField(default='Professional', max_length=50),
        ),
    ]
