# Generated by Django 6.1.1 on 2026-09-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_remove_profile_lifetime_emails_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='default_tone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.CharField(blank=True, default='Fresher', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='tech_stack',
            field=models.TextField(blank=True, help_text='e.g. React, Django, Python'),
        ),
    ]
